branches:
  except:
  - "/^wip/"
language: node_js
node_js:
- '8'
before_install:
- yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
script:
- yarn lint
- TZ="America/Los_Angeles" yarn test
after_success: yarn run coverage
env:
  global:
    secure: Zq1EuaT8hx7hVrKygiAlCIjsNMOWVf+/68Ce5TgZc2+dg5gAAeLUkuEyvFswD3yfpCf8s3FtQBubwOFz0y1cNsAzUGUrJqPLeSUnuB47IzKvtV9MK8gh1fN/AOHRH0L6tMTWs8aXKzS9U8uhBLH8PNKUoukbwqUhNlfzNGyxC8eOq6mwkIeSKNqRW0Wckd+gjLJtXhNTJlKDfhWjdMkzh0SOThhT1K0yj2DiMUT4nQO4IxvsFYa1YfQU70MkJxgpFQ5EavqThwKRUqxnMgOYkpGDD2FgasG9ZI/yp1B3ukq/bwhe9FqvYoEpvNIHk7ggx7w13QzrB0AkaxEqzayOYLS6TjL+X8c8eTuNved3+uNh8Q9wxTnpZemlOBSxOuSZMLRl89yuDSl0aSLZ1jt3h7YVHJpszWNGcpF+kfWe4zDx83rdS61nZQC2b11WfOixapddGohlSmGXx4/cuzAYaFGssLt4OBo1mKPco8I9PiUZOTjx3PVk3UqzoDrrxRf0aK7WPFfG6EafXeuQOepxJsvTYss3+GdCl5oCsLk3As+BTkie5h3d+yDEk6E7nVZaeGcTQKSYFL/6OR0xBaraVmynL6I4EEF2IG/umJB2pM1QOni53PC5C6jFynAPNa9f6v75BZ2pEXjg1E0k93RztjXCU4EaRkDxrz+aNon0Lyk=
notifications:
  slack:
    secure: hDYO02uW6mBw8BvwPol1Lo2Cr774ZDPvZX0XtWsDfDQ4H3PobrIum8bkNO7cFUZnb+SWATBfcqLNsifRxe7fJ61N/980IBgU5qK1FgOy5GXvgw7mtvrYiqLLj4j7z1hhHWFMEW0fQYxzQJvPwMn4ukvFnMJ71Sf/YtZvsiF40g92BfaU5tD7HL9+HR13k84C8Q+cgt1qZowjp6kxfxfx0iVyYJIfGMSkYLMZqXS0bn2MpmJkONarOmdY0U7rjgYddJYXMWAMLAwINTIYW5Y4zi/29dgpPoNGqC28natuCS7Fah+2OfkaNzN9gnKDZdSe2FahgtGyHpPJxLW5d+FxQSVv1257j1C+FW+SePVI4HkbeObHpzQ4NmPdjchQexpTEBrypnkSMBXaKA1yZ9hijnCW9TGTbD6INj2Mea4sxek1gOOhSa0mfP4y4L+4Wn8KAOD/sBcAZdtUJ2ACajyfMB2Haq0xvjVTxdC06sKsMyUA88OU0Te46dRkjcFKHYYVKoeazBi8xA/oJT5HwGiQRt4bd8ANz8SVPlEZHH6NkwD/fEHpx9OGIIriAm3rINsdA1w52PUfRQE2ksBW+278dHFrvwzL4tTSDbU3IrMs9rOvL8RtNf66kMkmSdqFxCCQEMXyjJW9YY0Mdom/4pNxFBiFWIk1WCZfgM4xi4En6/8=
